insert into Products (name, category_id) values ('Bread', 1);
insert into Products (name, category_id) values ('Iwisa Pap 5kg', 2);
insert into Products (name, category_id) values ('Chakalaka Can', 3);
insert into Products (name, category_id) values ('Gold Dish Vegetable Curry Can', 3);
insert into Products (name, category_id) values ('Coke 500ml', 4);
insert into Products (name, category_id) values ('Cream Soda 500ml', 4);
insert into Products (name, category_id) values ('Fanta 500ml', 4);
insert into Products (name, category_id) values ('Mixed Sweets 5s', 5);
insert into Products (name, category_id) values ('Heart Chocolates', 5);
insert into Products (name, category_id) values ('Shampoo 1 litre', 6);
insert into Products (name, category_id) values ('Soap Bar', 6);
insert into Products (name, category_id) values ('Imasi', 7);
insert into Products (name, category_id) values ('Milk 1l', 7);
insert into Products (name, category_id) values ('Apples - loose', 8);
insert into Products (name, category_id) values ('Bananas - loose', 8);
insert into Products (name, category_id) values ('Top Class Soy Mince', 9);	
insert into Products (name, category_id) values ('Valentine Cards', 10);
insert into Products (name, category_id) values ('Rose (plastic)', 10);